services:
  kafka:
    image: confluentinc/confluent-local:7.5.0
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,LOCAL:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,LOCAL://localhost:9091
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LISTENERS=INTERNAL://kafka:9092,LOCAL://0.0.0.0:9091,CONTROLLER://kafka:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
    expose:
      - 9091
      - 9092
      - 9093
    ports:
      - 9091:9091
    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics --bootstrap-server kafka:9092 --list" ]

  # Will create the topics upon startup
  kafka_init:
    image: confluentinc/confluent-local:7.5.0
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./scripts:/scripts
    command: >
      /scripts/create-topics.sh kafka:9092 test-topic topic-2p:2 topic-12p:12 

  kafka-ui:
    image: provectuslabs/kafka-ui
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8002:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
